name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk --release
      - name: Upload APK to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/app-release.apk
          tag: release-${{ github.sha }}
          overwrite: true
          body: "Release version ${{ github.sha }}"

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build ios --release --no-codesign
      - run: mkdir Payload
        working-directory: build/ios/iphoneos
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos
      - name: Zip output
        run: zip -qq -r -9 app-debug.ipa Payload
        working-directory: build/ios/iphoneos
      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/app-release.ipa
          tag: release-${{ github.sha }}
          overwrite: true
          body: "Release version ${{ github.sha }}"