name: Build and Verify on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build ios --release --no-codesign
      - name: Create IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/ios/iphoneos/Runner.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $PWD/build/ios/iphoneos \
            -allowProvisioningUpdates
      - uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: build/ios/iphoneos/Runner.ipa
